steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/voldisloc-repo/voldisloc:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/voldisloc-repo/voldisloc:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'voldisloc',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/voldisloc-repo/voldisloc:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--memory', '1Gi',
        '--allow-unauthenticated',
        '--service-account', 'cloud-run-deployer@voldilsloc.iam.gserviceaccount.com'
      ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/voldisloc-repo/voldisloc:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
